Feature/change playlist
iagolaguna/vscodefy pull request #8
Opened 2019-02-16 22:29 UTC by elizeugba

I finally splitted the features, now I'm pulling the change playlist. I tested it on Windows and my smartphone (Android).

2019-03-20 13:54 UTC, brenonaraujo commented
Damn, I really would like has this feature, seems pretty nice!

2019-03-20 13:56 UTC, gustavomerini commented
+1

2019-03-24 22:27 UTC, iagolaguna commented
Sorry for the late guys, @elizeugba you forget to put the command in the commands in package.json and your feature isn't working, please fix this, and have some glitch because the owner of the playlist is showing as `null` look this too.

2019-03-28 13:31 UTC, iagolaguna requested changes

2019-03-28 13:31 UTC, iagolaguna commented on src/commands/commands.js
> +      description: `Owner: ${playlist.owner.display_name}`,
if Owner doesn't exist will you show `null` for the user ?

2019-03-28 13:31 UTC, iagolaguna commented on src/extension.js
> +    buttonCommand: 'vscodefy.change_playlist'
please fix `change_playlist` to `changePlaylist` to maintain the pattern

2019-03-28 13:31 UTC, iagolaguna commented on src/extension.js
> +    command: 'vscodefy.change_playlist',
here the same

2020-04-18 03:00 UTC, closed without merging